version: "3"
services:
  db:
    image: mysql
    volumes:
      #- ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: webshop
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - web

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - 8083:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - web
  php:
    build: ./docker/php/
    expose:
      - 9000
    volumes:
      - ./src:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - web

  webserver:
    image: nginx:latest
    depends_on:
      - php
      - db
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    networks:
      - web

networks:
  web:
